=== vonop1/ch.bfh.bti7301.w2013.FuSi/XML/ConfigSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name ="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="objList" type="tyObjList"/>
        <xs:element name="walkerList" type="tyWalkerList"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


    <xs:complexType name="tyObjList">
      <xs:sequence>
        <xs:element name="obj" minOccurs="0" maxOccurs="unbounded" type="tyObj"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tyObj">
        <xs:sequence>
            <xs:element name="point" minOccurs="2" maxOccurs="unbounded" type="tyPoint"/>
        </xs:sequence>
    </xs:complexType>


  <xs:complexType name ="tyPoint">
    <xs:attribute name ="x" use ="required" type="xs:nonNegativeInteger"/>
    <xs:attribute name ="y" use ="required" type="xs:nonNegativeInteger"/>
  </xs:complexType>

  <xs:complexType name ="tyWalkerList">
    <xs:sequence>
      <xs:element name="walker" minOccurs="0" maxOccurs="unbounded" type="tyWalker"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name ="tyWalker">
    <xs:sequence>
      <xs:element name="source" type="tyPoint"/>
      <xs:element name="target" type="tyPoint"/>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== vonop1/ch.bfh.bti7301.w2013.FuSi/XML/one Rect.xml
<?xml version="1.0" encoding="utf-8"?>
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ConfigSchema.xsd">
  <objList>
    <obj>
      <point x="210" y="70"/>
      <point x="410" y="70"/>
      <point x="410" y="110"/>
      <point x="210" y="110"/>
    </obj>
  </objList>
  <walkerList>
    
  </walkerList>
</Config>

=== vonop1/ch.bfh.bti7301.w2013.FuSi/XML/Config.xml
<?xml version="1.0" encoding="utf-8"?>
<objList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="configSchema.xsd">
  <obj>
    <point x="110" y="50"/>
    <point x="410" y="50"/>
    <point x="410" y="100"/>
    <point x="120" y="100"/>
  </obj>
    <obj>
        <point x="110" y="250"/>
        <point x="210" y="200"/>
        <point x="160" y="300"/>
    </obj>
    <!-- <obj>
        <point x="310" y="100"/>
        <point x="360" y="20"/>
        <point x="450" y="150"/>
        <point x="380" y="300"/>
        <point x="330" y="280"/>
    </obj> -->
</objList>

=== vonop1/ch.bfh.bti7301.w2013.FuSi/XML/EngpassWelt2.xml
<?xml version="1.0" encoding="utf-8"?>
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ConfigSchema.xsd">
    <objList>
        <obj>
            <point x="220" y="0"/>
            <point x="310" y="0"/>
            <point x="310" y="100"/>
            <point x="220" y="100"/>
        </obj>
        <obj>
            <point x="250" y="120"/>
            <point x="220" y="500"/>
            <point x="310" y="500"/>
        </obj>
    </objList>
    <walkerList>
        <walker>
            <source x="20" y="20"/>
            <target x="520" y="300"/>
        </walker>
        <walker>
            <source x="20" y="300"/>
            <target x="520" y="20"/>
        </walker>
        <walker>
            <source x="20" y="100"/>
            <target x="520" y="300"/>
        </walker>
        <walker>
            <source x="20" y="130"/>
            <target x="520" y="300"/>
        </walker>
        <walker>
            <source x="20" y="200"/>
            <target x="520" y="300"/>
        </walker>
        <walker>
            <source x="520" y="300"/>
            <target x="20" y="30"/>
        </walker>
        <walker>
            <source x="520" y="20"/>
            <target x="20" y="330"/>
        </walker>
        <walker>
            <source x="520" y="300"/>
            <target x="20" y="130"/>
        </walker>
        <walker>
            <source x="520" y="300"/>
            <target x="20" y="160"/>
        </walker>
    </walkerList>
</Config>
